services:
  postgres_db:
    restart: unless-stopped
    image: postgres:16
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE__DB}
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
    env_file:
      - .env
    ports:
      - "${DATABASE__PORT}:5432"

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - .:/build
    environment:
      - DATABASE__HOSTNAME=postgres_db
      - DATABASE__PORT=5432
    env_file:
      - .env
    depends_on:
      - postgres_db
    command: tail -f /dev/null

volumes:
  postgres_db:
